##################################################
# Run GitHub Super Linter against code base #
##################################################

---
name: GitHub Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: GitHub Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository 🚦
        uses: actions/checkout@main

      - name: Run GitHub Super Linter 🚀
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: /
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
